### PR TITLE
Enable to add comments

### PR DESCRIPTION
**Pull request by takenory**
This is a feature addition to realize issue #30.

### CODE REVIEW

**Review by ishikawa999 — COMMENTED** [review]
I have checked the code and verified that it works.
It looks good.

I especially liked the fact that having separate allowed_ips_with_comments and allowed_ips does not affect processing speed because there is no need to move the process of excluding comments when actually accessing the site.

Will changes to util.rake create another pull request?

**Review by ishikawa999 — APPROVED** [review]

**Comment by takenory** [comment]
Thanks for the review @ishikawa999.

> Will changes to util.rake create another pull request?

I will add a commit to this PR.

**Comment by takenory** [comment]
@ishikawa999 
Commited dcb5b0c . Please review it.

**Comment by ishikawa999** [comment]
> This is a feature addition to realize issue #30.

Sorry for the late review. I don't think there is any problem.

**Review by maeda-m — COMMENTED** [review]
@takenory 
Thank you for the pull request. 

It's great that the 'Allowed IP addresses' becomes easier to manage with effective commenting. I have confirmed that it works in my environment below. I was able to register an example of #30 in the browser.

```
Environment:
  RedMica version     2.4.1.stable (based on Redmine 5.1.1.devel)
  Ruby version        3.2.2-p53 (2023-03-30) [x86_64-linux]
  Rails version       6.1.7.6
  Environment         development
  Database adapter    PostgreSQL
```

I confirmed that delete and show_with_comments in util.rake work even with comments. 

That's fantastic 👍 

---

I have one suggestion for util.rake. It would be great to have add_with_comments similar to show_with_comments for add. Having a CLI that can also add comments like the following would be convenient for me, as I won't need to launch a browser.

Usage:
```console
$ bin/rails redmine_ip_filter:filters:add_with_comments ADDR_WITH_COMMENTS='
> # Our offices
> 192.0.2.1  # headquarter
> 192.0.2.100  # branch A
> 
> 198.51.100.21 # Foo Corporation
> '
```

Example implementation:
```ruby
desc 'Add IP addresses to the allowed IP addresses with comments'
task :add_with_comments => :environment do
  filter_rule = FilterRule.find_or_default
  address_with_comments = ENV['ADDR_WITH_COMMENTS']
  if address_with_comments.blank?
    abort 'IP addresses to add must be specified with ADDR_WITH_COMMENTS environment variable'
  else
    filter_rule.allowed_ips = ([filter_rule.allowed_ips_with_comments, address_with_comments]).join("\n")
  end
  unless filter_rule.save
    STDERR.puts filter_rule.errors.messages[:base]
    exit 1
  end
  puts "ADD:\n#{address_with_comments}"
end
```

I would appreciate your opinion on this.

**Review by maeda-m — APPROVED** [review]
@takenory Thank you for the great PR.
I've confirmed that the feature to add comments works in RedMica v2.4.1, so it looks good to me.

The `add_with_comments` I suggested was about a different topic, so I wrote it in #42.
I apologize.

**Comment by takenory** [comment]
Thanks to all the reviewers!
I'm merging this PR change.

**Pull request merged**
